name: issue and PR lifecycle

on:
  issues:
    types: [opened, labeled, closed]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  schedule:
    - cron: '0 9 * * *'

permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  lifecycle:
    uses: ./.github/workflows/lifecycle.yml
    with:
      brand_name: "Common"
    secrets: inherit
